# Generated by Django 4.2.5 on 2023-10-31 11:31

import api.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('identification_number', models.CharField(max_length=14, primary_key=True, serialize=False, unique=True, verbose_name='Identification Number')),
                ('photograph', models.CharField(blank=True, max_length=400, verbose_name='Photograph')),
                ('typee', models.CharField(blank=True, max_length=30, verbose_name='Type')),
                ('account', models.CharField(blank=True, max_length=7, verbose_name='Account')),
                ('name', models.CharField(blank=True, max_length=80, verbose_name='Name')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Membro')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_usuarios_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='custom_usuarios_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', api.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('agency', models.CharField(blank=True, max_length=4, verbose_name='Agency')),
                ('number', models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('typee', models.CharField(max_length=10, verbose_name='Type')),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='CreditLimit')),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('receive_account', models.CharField(max_length=7, verbose_name='Account')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('typee', models.CharField(max_length=10, verbose_name='Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_account', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='Phone')),
                ('prefix_number', models.CharField(max_length=2, verbose_name='Prefix Number')),
                ('area_code', models.CharField(max_length=2, verbose_name='Area Code')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_phones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NaturalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('birthdate', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, unique=True, verbose_name='RG')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_naturalPerson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Installment Value')),
                ('times', models.IntegerField(verbose_name='Times')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('typee', models.CharField(max_length=10, verbose_name='Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_loan', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_name', models.CharField(max_length=80, verbose_name='Fantasy Name')),
                ('establishment_date', models.DateField()),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('im', models.CharField(max_length=20, unique=True, verbose_name='IM')),
                ('ie', models.CharField(max_length=20, unique=True, verbose_name='IE')),
                ('legalNature', models.CharField(max_length=80, verbose_name='Legal Nature')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_legalPerson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_investment', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=20, verbose_name='Transaction')),
                ('positive_negative', models.CharField(max_length=1, verbose_name='Positeve or Negative')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Value')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('number', models.CharField(max_length=7, verbose_name='Number')),
                ('installments', models.IntegerField(blank=True, null=True, verbose_name='Installments')),
                ('installment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Installment Value')),
                ('date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_historic', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('number', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, unique=True, verbose_name='Number')),
                ('create_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('verification_number', models.CharField(blank=True, max_length=3, verbose_name='Verification Number')),
                ('status', models.BooleanField(verbose_name='Status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_card', to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('city', models.CharField(max_length=80, verbose_name='City')),
                ('street', models.CharField(max_length=80, verbose_name='Street')),
                ('neighborhood', models.CharField(max_length=80, verbose_name='Neighborhood')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
