# Generated by Django 4.2.5 on 2023-10-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Installments'),
        ),
    ]
