# Generated by Django 4.2.5 on 2023-11-01 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_transaction_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='photograph',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Photograph'),
        ),
    ]
